services:
  api:
    build: ./api
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./api:/app
  web:
    image: nginx
    ports:
        - 8080:80
    volumes:
        - ./html:/usr/share/nginx/html
