- name: check/init swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}:{{ advertise_addr_port }}"
  register: __output_swarm
  when: inventory_hostname in groups['managers'][0]

- name: install manager
  docker_swarm:
    state: join
    timeout: 60
    advertise_addr: "{{ advertise_addr }}:{{ advertise_addr_port }}"
    join_token: "{{ hostvars[groups['managers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager']}}"
    remote_addrs: "{{ advertise_addr }}"
  when: inventory_hostname in groups['managers'] and inventory_hostname not in groups['managers'][0]

- name: install worker
  docker_swarm:
    state: join
    timeout: 60
    advertise_addr: "{{ advertise_addr }}:{{ advertise_addr_port }}"
    join_token: "{{ hostvars[groups['managers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ advertise_addr }}"
  when: inventory_hostname in groups['workers']
